# Tether is the ultimate leashing solution.
# You can leash any mob or player, and can take full control over leashing across your server with a
# multitude of configuration options and integrations.

# If set to true, the entity blacklist will be ignored and the whitelist will be used.
use-whitelist-over-blacklist: false

# Write entities that you don't want leashable here.
# Tip: You can also write DEFAULT_LEASHABLE_ENTITIES to target all entities that are leashable by default.
entity-blacklist:
  - EXAMPLEMOB

# Entities written here will be the only entities leashable.
# *Note: Requires that 'use-whitelist-over-blacklist' is set to true above.
# Tip: You can also write DEFAULT_LEASHABLE_ENTITIES to target all entities that are leashable by default.
entity-whitelist:
  - EXAMPLEMOB

# Player Leash Settings
player-leash:
  # Should players be leashable? (Also requires the player leashing to have the tether.use.players permission).
  enabled: false
  # Should leashed players be able to escape by crouching?
  escapable: true
  # Should players receive a message when they've been leashed?
  message-on-leashed: true
  # Prevents leashed players from leashing other players.
  prevent-nesting: false

# Should Tether hook into the following land management plugins?
# (Requires restart upon change).
hooks:
  griefprevention: false
  towny: false
  lands: false
  griefdefender: false
  residence: false

# Messages
messages:
  prefix: "&8[&6Tether&8] &r"
  reload: "&7Tether has been reloaded!"
  no-permission: "&cYou do not have permission!"
  leash-target-in-protected-land: "&7Leash target is in protected land."
  player-leashed-escapable: "&7You've been leashed! Press &6crouch &7to escape."
  player-leashed-not-escapable: "&7You've been leashed!"
  cannot-leash-riding-player: "&7You cannot leash players that are riding an entity."
  prevent-nesting: "&7You cannot leash a player while your are leashed."