name: Tether
version: '${project.version}'
main: dev.naspo.tether.Tether
api-version: 26.2
author: Naspo
description: The ultimate leashing solution. Leash any mob or player and take full control over leashing across your server.

softdepend:
  - GriefPrevention
  - Towny
  - Lands
  - GriefDefender
  - Residence
  - WorldGuard

commands:
  tether: